### PR TITLE
Remove proprietary notices about video

### PR DESCRIPTION
**Pull request by srxr**
Ref: #39

### CODE REVIEW

**Comment by prologic** [comment]
What if we make it configurable?￼

**Comment by srxr** [comment]
> What if we make it configurable?￼

Sounds good! I'll make it happen.

**Review by prologic — DISMISSED** [review]
Nice!

**Comment by prologic** [comment]
Not sure how I missed this. Sorry @srxr re-approved and merged!

**Review by prologic — APPROVED** [review]

**Pull request merged**
